In [2]:
import tensorflow as tf
tf.InteractiveSession()

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [12]:
a=tf.zeros((4,4))
a.eval()



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [15]:
b= tf.ones((5,3,4))
b.eval()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [23]:
c= tf. fill((2,3), value =9.)
c.eval()


array([[9., 9., 9.],
       [9., 9., 9.]], dtype=float32)

In [25]:
a= tf.constant(9)
a.eval()

9

In [34]:
a= tf.random_normal((2,3), mean=0, stddev=1)
a.eval()

array([[-0.6744577 , -1.768083  ,  0.33629963],
       [-1.535912  ,  1.337916  ,  0.348098  ]], dtype=float32)

In [39]:
a= tf.ones((2,2))
b= tf.ones((2,2))
c= a+b
c.eval()

f= 2*c
f.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [67]:
c= tf.fill((2,2), value=3)
d = tf.fill((2,2), value =2)
e = c+d
e.eval()



array([[5, 5],
       [5, 5]])

In [71]:
f=c*d
f.eval()

array([[6, 6],
       [6, 6]])

In [68]:
i= tf.matmul(c,d)
i.eval()

array([[12, 12],
       [12, 12]])

In [50]:
g= tf.eye(5)
g.eval()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [52]:
h= tf.range(1,6,1)
h.eval()

array([1, 2, 3, 4, 5])

In [55]:
r=tf.diag(h)
r.eval()

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [64]:
c= tf.ones((2,3))
c.eval()




array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [72]:
at=tf.matrix_transpose(c)
at.eval()

#casting functions such as tf.to_double(), tf.to_float(), tf.to_int32(), tf.to_int64(),

array([[3, 3],
       [3, 3]])

In [77]:
a= tf.ones((2,2))
a.eval()


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [82]:
b= tf.ones((2,2), dtype=tf.int32)
b.eval()
c=tf.to_float(b)
c.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [87]:
sess = tf.Session()
a = tf.ones((2,2))
b= tf.matmul(a,a)
b.eval(session=sess)
sess.run(b)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [102]:
a= tf.Variable(tf.ones(2,2))
a

<tf.Variable 'Variable_4:0' shape=(2,) dtype=float64_ref>

In [100]:
a.eval()

FailedPreconditionError: Attempting to use uninitialized value Variable_3
	 [[{{node _retval_Variable_3_0_0}}]]

In [109]:
sess.run(a.assign(tf.zeros(2,2)))
sess.run(a)

array([0., 0.])